tank_animation = {
    "indexes":["barrel", "body"],
    "idle":{
        "duration":0,
        "initial_frame":{
            "barrel":{
                "image":"0"
            }
        }
    },
    "shoot_bullet":{
        "duration":0.2,
        "initial_frame":{
            "barrel":{
                "image":"0"
            }
        },
        "frames":[
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"1"
                    }
                }
            },
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"2"
                    }
                }
            },
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"3"
                    }
                }
            },
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"4"
                    }
                }
            }
        ]
    }
}

animations = {
    "tank":tank_animation
}