tank_animation = {
    "shoot_bullet":{
        "duration":0.2,
        "indexes":["barrel"],
        "initial_frame":{
            "barrel":{
                "image":"0"
            }
        },
        "frames":[
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"1"
                    }
                }
            },
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"2"
                    }
                }
            },
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"3"
                    }
                }
            },
            {
                "delay":0.25,
                "properties":{
                    "barrel":{
                        "image":"4"
                    }
                }
            }
        ]
    }
}